const config = {
    local: {
        root_url_prefix: '',
        root_url: '',
        api_url: 'http://localhost:7003'
    },
    development: {
        root_url_prefix: '',
        root_url: '',
        api_url: 'http://localhost:7003'
    },
    production: {
        root_url_prefix: '/runtest',
        root_url: '',
        api_url: 'https://cms-pdmv-dev.cern.ch/runtest_api'
    }
};
exports.root_url_prefix =
    config[process.env.NODE_ENV || 'development']['root_url_prefix'];

exports.api_url = config[process.env.NODE_ENV || 'development']['api_url'];

exports.components = [
    'cms',
    'castor',
    'csc',
    'dt',
    'ecal',
    'es',
    'hcal',
    'hlt',
    'l1t',
    'l1tcalo',
    'lumi',
    'pix',
    'rpc',
    'strip',
    'ctpps'
];

exports.offline_columns = [
    'occupancy',
    'integrity',
    'strips',
    'timing',
    'efficiency',
    'gasgains',
    'resolution',
    'segments',
    'tf',
    'triggergpe',
    'rp45-220',
    'rp45-cyl',
    'rp56-210',
    'rp56-220',
    'rp56-cyl',
    'ebp',
    'ebm',
    'eep',
    'eem',
    'es',
    'esp',
    'esm',
    'analysis',
    'collisions',
    'laser',
    'tpg',
    'noise',
    'preshower',
    // 'timing',
    'hb',
    'he',
    'hf',
    'ho0',
    'ho12',
    'hb ls',
    'he ls',
    'hf ls',
    'ho0 ls',
    'ho12 ls',
    'bjets',
    'electrons',
    'hlt global',
    'jetmet',
    'muons',
    'photons',
    'tau',
    'technical',
    'bcs tech',
    'bptx tech',
    'e gamma',
    'energy sums',
    'hf rings',
    'hf tech',
    'l1tcalo',
    'l1tmu',
    'muon csc',
    'muon dt',
    'muon rpc',
    'rpc tech',
    'software',
    'rpc',
    'hv',
    'lv',
    'feb',
    // 'noise',
    'elog',
    'pix',
    'strip',
    'track'
];
